name: velero-custom-plugins-test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install gomock and mockgen
      run: |
        go install github.com/golang/mock/mockgen@v1.6.0
        go install github.com/golang/mock/gomock@v1.6.0

    - name: Generate mock-data
      run: |
        mockgen -destination=mocks/mock_configmap_client.go -package=mocks k8s.io/client-go/kubernetes/typed/core/v1 ConfigMapInterface

    - name: Build
      run: go build -v ./...